site_name: etki Tech Network
theme: united
google_analytics: ['UA-169291387-2', 'auto']

nav:
  - Home: 'index.md'
  - Join us: 'join_us.md'
  - Contact us: 'contact.md'
  - Data Protection: 'dataprotection.md'
  - Imprint: 'imprint.md'
  - License: 'license.md'
